### ISSUE TITLE
Any Updates Planned

### ISSUE THREAD

**Issue by Badfish1** [irbujam/ss_log_event_monitor#2]
Hi,  Just wondering whether you have any plans to update this.  It's been working great for me until the latest release of subspace (Jul-16) which included changes to the metrics.  It's still telling me the status of the node and the farmers, but not including any data on Uptime or Rewards etc.

**Comment by avselang** [comment]
me too

**Comment by irbujam** [comment]
new version released addressing endpoint metrics changes in autonomys/subspace July 16 build

**Comment by avselang** [comment]
> new version released addressing endpoint metrics changes in autonomys/subspace July 16 build. Please report back if the new version of monitor works for you. The updated monitor is backwards compatible and should also run with prior subspace release versions.

it  works

**Comment by Badfish1** [comment]
Yes works perfectly for me.  Thanks for the quick response.

**Comment by Badfish1** [comment]
Yes works perfectly for me. Thanks for the quick response.
