### ISSUE TITLE
设置“BufferSize”时发生异常

### ISSUE THREAD

**Issue by avselang** [irbujam/ss_log_event_monitor#3]
设置“BufferSize”时发生异常:“无法设置缓冲区大小，因为指定的大小过大或过小。
参数名: value
实际值是 2,3000。”
所在位置 C:\ss_log_event_monitor-main-10-23\subspace_advanced_CLI_monitor.ps1:1252 字符: 2
+     $host.UI.RawUI.BufferSize = New-Object System.Management.Automati ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting

**Comment by irbujam** [comment]
please give v0.1.5 a try and let me know if this resolves your issue.
